### PR TITLE
Logo design

### PR DESCRIPTION
**Pull request by error404-sp**
#1

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Hi @error404-sp ! Apologies for a slow follow-up here, and thank you for your contribution!

I added a new folder in this Github repo, `design/`: intent is that all PRs can add necessary files under there, but first creating sub-folder with Github user name. So you would create folder

    design/error404-sp 

and under that may create other folders, or add files directly there. This way I can merge PRs and to count for Hacktoberfest, but in case there might be multiple contributors files do not overlap. I can also then point Jackson community members to submissions and get feedback on what they like; sometimes there are good suggestions for changes and so on.

Would it be possible for you to change your Pull Request to move files under suggested structure?

**Comment by cowtowncoder** [comment]
@error404-sp Thank you! I moved these to under `design/error404-sp`, renamed files. I think this would qualify for two PRs actually; if you want to create another PR (even if just for adding `README.md` under `design/error404-sp/`), happy to merge to give you credit for 2.

I also really like ClassMate one; thank you for contribution again!

**Comment by error404-sp** [comment]
Thank you so much @cowtowncoder , I am glad it was helpful.I had tried to move those but couldn't. I would really appreciate if you could provide me some docs to learn to do so.
Thanks

**Comment by cowtowncoder** [comment]
@error404-sp np. It depends on how you interact with git: I use command-line client and so I can either move files (create directory, move, rename) and use `git add`, or use git command itself (`git mv`).
So basically you create new structure locally and commit changed file locations to your fork.
There may be some easier ways but that is how I do it.

**Comment by error404-sp** [comment]
Thank you, I use command line too but was unaware of git mv command

**Comment by error404-sp** [comment]
Thanks @cowtowncoder , I use terminal too but was unaware of git mv command

**Pull request merged**
